### ISSUE TITLE
About OOK pulses & spectrum

### ISSUE THREAD

**Issue by JefFan4YC** [edsonportosilva/OptiCommPy#14]
Hi, @edsonportosilva

I'm testing the basic_OOK codes shown in the ./examples, and the figures seem like:

![image](https://github.com/edsonportosilva/OptiCommPy/assets/75775590/1dc04675-e151-4bc1-a987-c3496ee09ff5)

Such results, unlike the preview in basic_OOK_transmission notebook, show a different pulse shaping method leading to abnormal spectrum.

![image](https://github.com/edsonportosilva/OptiCommPy/assets/75775590/75d17a99-507e-4cf7-9a50-911827187083)

With no revision of original codes, I guess it comes from an alternative PulseShape in the up-to-date version. May I know some tips to solve this? Thanks.

**Comment by JefFan4YC** [comment]
Ah, I figure out it's the `pnorm` from `optic.dsp` leading to this variation. Might be necessary to update it to show the notebook results.

**Comment by edsonportosilva** [comment]
Hello @JefFan4YC,

This notebook will be changed in an upcoming update of the repository. The issue is that

**Comment by JefFan4YC** [comment]
@edsonportosilva Yes, it seems a proper MZM input is necessary. Again, thanks for your help and looking forward to the new update!
