### ISSUE TITLE
Some questions about rolloff, DAC, upsample

### ISSUE THREAD

**Issue by biueo** [edsonportosilva/OptiCommPy#16]
1. Rolloff cannot be zero in this repo.Error while rolloff is setted to zero in function rcFilterTaps() or rrcFilterTaps.
2. Upsample factor cannot be a decimal such as 1.2. 1.5 these are often used in practice
3. In this repository, DAC, the zero-order hold, and the quantization stages of DAC have not been taken into account. These elements can have an impact on the spectrum and are also crucial in practical simulations.

**Comment by edsonportosilva** [comment]
Hello @biueo,

1. Rolloff cannot be zero in raised cosine or root-raised cosine for obvious reasons. A Nyquist pulse with zero-rolloff is a sinc pulse, which has no practical relevance.
2. The functions resample and clockSamplingInterp (https://opticommpy.readthedocs.io/en/latest/dsp.html#core-digital-signal-processing-utilities-optic-dsp-core) can be used to set arbitrary sampling rates.
3. See the functions quantizer (https://opticommpy.readthedocs.io/en/latest/generated/optic.dsp.core.quantizer.html) and the adc model (https://opticommpy.readthedocs.io/en/latest/generated/optic.models.devices.adc.html#optic.models.devices.adc)
