### ISSUE TITLE
FEC for WDM

### ISSUE THREAD

**Issue by Echo-cwb** [edsonportosilva/OptiCommPy#4]
Hello author, I would like to ask if the fec in your code only supports error correction of AWGN channel, and cannot correct error for WDM fiber channel

**Comment by Echo-cwb** [comment]
I would like to know how I can modify it to implement the FEC of the WDM system? Thank you very much for your help.

**Comment by edsonportosilva** [comment]
Hi. First, the soft-LDPC FEC used in coherent optical transmission systems is designed for AWGN channels. When applied to the fiber channel, the output of the coherent receiver is assumed to be the output of an AWGN channel. Second, an example of how to use the LDPC coding and decoding functions is given in this notebook [test_fec.ipynb](https://github.com/edsonportosilva/OptiCommPy/blob/main/examples/test_fec.ipynb). To perform WDM simulations with LDPC FEC, you need to write a function as simpleWDMTx in [tx](https://github.com/edsonportosilva/OptiCommPy/blob/main/optic/tx.py) including the LDPC encoder to generate the LDPC encoded modulation signals. To decode the received data, it is necessary to add the LDPC decoder after the carrier recovery block in the receiver DSP.
