### ISSUE TITLE
FEC for WDM

### ISSUE THREAD

**Issue by Echo-cwb** [edsonportosilva/OptiCommPy#5]
Hello dear author, I modified the code according to your thoughts, but there was a problem with LDPC demodulation, his FEC did not work, I would like to ask if you can help me. Thank you so much!
in tx:
![image](https://user-images.githubusercontent.com/64060578/204294858-6e3237c9-5220-499a-b247-e11164047011.png)
![image](https://user-images.githubusercontent.com/64060578/204295367-5b7f5602-0db8-4f37-a842-b75abf4e1132.png)
CPR:
![image](https://user-images.githubusercontent.com/64060578/204295641-a1be4930-9614-420f-b6c7-640baba95dcc.png)

After CPR:
![image](https://user-images.githubusercontent.com/64060578/204295562-fc030059-38f9-4c53-81d2-64cba20de57a.png)

**Comment by Echo-cwb** [comment]
https://colab.research.google.com/drive/1D0dlAILsyHGVoLstlFMSYF5vtxO2tk3t#scrollTo=4f6650fe
This link is my code 
[test14_compressed.txt](https://github.com/edsonportosilva/OptiCommPy/files/10104338/test14_compressed.txt)

**Comment by edsonportosilva** [comment]
Hello. Your code is very messy and one cannot understand what you're trying to do. Again, the only thing you need to do is to generate an LDPC-coded bit sequence at the transmitter and add the decoder at the receiver. From what I have seen, you are changing other parts of the code, and that is why you are getting errors. If you want help, you need to be more specific about the problems you have.
